name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
          fail-fast: false
          matrix:
            os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Download Words
      run: mkdir $HOME/.wordle_solver && curl https://gist.githubusercontent.com/PepperLola/bbc3512ba937a56572219536b60da4fd/raw/1295fc03cabfcc7d2bd290dc75fc28a8569dc3fe/words.txt > $HOME/.wordle_solver/words.txt
    - name: Run tests
      run: cargo test --verbose
    - uses: actions/upload-artifact@v3
      with:
        name: wordle_solver
        path: target/release/wordle_solver
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.run_id }}
        name: Release ${{ github.run_id }}
        prerelease: false
        files: ./target/release/wordle_solver
